<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3f39a90a-c53d-4b41-ad77-0c452b36a0a0</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../src/CleanArc.Application/CleanArc.Application.csproj" />
    <ProjectReference Include="../src/CleanArc.Infrastructure/CleanArc.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.1" />
  </ItemGroup>

</Project>
